### ISSUE TITLE
Ознакомиться с макетом и техническими требованиями

### ISSUE THREAD

**Issue by xdpugachevx** [xdpugachevx/xstupidkidzx_project#1]
Перед началом работы продублируйте макет к себе в аккаунт Figma: https://www.figma.com/file/hjpEJNXCQkiCYQFOI8gb0L/Web-Start-%E2%80%94-Easy-(Rus)?node-id=0%3A1

Внутри макета есть комментарии, чтобы переключиться в режим комментирования, нажмите горячую клавишу  С  на клавиатуре. Или выберите этот пункт в меню: 
![image](https://user-images.githubusercontent.com/1089819/109813337-a7d15180-7c46-11eb-99c1-66787ea4ef74.png)

В комментариях указаны интерактивные элементы и их поведение при клике или наведении курсора. Внимательно прочитайте все комментарии к макету. 

## Технические требования к верстке
Каждая сверстанная часть макета (отдельная задача) будет проверяться согласно требованиям приведенным ниже.

### Адаптивность 
Ваша веб-страница должна корректно отображаться на мобильных устройствах, планшетах, ноутбуках и больших экранах. Мы будем проверять вашу верстку на экранах шириной от 320px до 1920px. Проверьте, настроен ли meta-тег viewport и заданы ли правила @media для вашего сайта. 

Если отсутствует макет для адаптивной верстки для какого-то элемента, нужно создать адаптив самостоятельно. Проверьте свой сайт на имитации различных устройств, в вертикальной и горизонтальной ориентации: пользователю должно быть комфортно на любом из них.

### Валидность 
Ваш код не должен содержать ошибок или предупреждений при проверке на валидаторе. Проверять ваш код мы будем через [validator.w3.org](http://validator.w3.org/). В консоли браузера не должно быть ошибок. 

### Переполняемость блоков 
Текстовые блоки на сайте должны быть рассчитаны на текст большей длины. Например, если вы создали кнопку, где всего одно слово, проверьте, как себя будет вести кнопка, если вставить 4-5 слов. Верстка не должна ломаться, элементы не должны наезжать друг на друга из-за переполненности текстом. Текст не должен вываливаться за границы блока. Можно растягивать блок с текстом. А можно скрыть текст, который не поместился, но оставить прокрутку колесиком мыши. 

### Нет горизонтальной прокрутки 
На вашем сайте не должно быть горизонтального скролла. Если это случилось, значит какой-то элемент “вываливается” из тела документа. Надо это исправить, иначе вы не пройдете проверку. 

### Соответствие макету 
Шрифты и цвета должны соответствовать макету: начертания, размеры, веса. Для размеров элементов и отступов допускаются незначительные отклонения от макета. 

Сверьте свою верстку с дизайн-макетом. Используйте для этого плагин [Perfect Pixel](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=ru) для Google Chrome. Расхождения с макетом должны быть не более чем 10px.

### Методология БЭМ 
Все названия классов, идентификаторов, переменных, функций должны отражать суть или функцию этих элементов. Писать названия в транслитерации нельзя. Например, если вы создадите в разметке классы zagolovok, otzivi, tekst — вы не пройдете проверку. 

При работе с HTML разметкой, используйте методологию БЭМ. Мы будем проверять ваш код на наличие ошибок БЭМ через [yoksel.github.io/html-tree](https://yoksel.github.io/html-tree/). 

### Скорость загрузки
Ваш сайт должен пройти проверку на быстродействие через [Google Pagespeed Insights](https://developers.google.com/speed/pagespeed/insights/?hl=RU). Необходимо набрать больше 60 баллов. 

### Стили интерактивных элементов
Для интерактивных элементов должны быть предусмотрены стили при наведении, клике и т.д. Если в дизайн-макете предусмотрено поведении при клике, состоянии фокуса и т.д., нужно применить эти стили. Проследите, чтобы стили при наведении не работали на экранах меньше 992px. 

Все пункты меню должны по нажатию перемещать пользователя к соответствующей секции на сайте. Также нужно реализовать кнопку “”вверх”

### Кроссбраузерная верстка 
Ваш сайт должен одинаково хорошо отображаться в последних версиях браузеров:
* Mozilla FireFox
* Google Chrome
* Opera
* Яндекс.Браузер
* Edge 
* Safari (Mac OS)

По желанию можете проверить в браузере IE11, некоторые заказчики все еще требуют его поддержку. Но мы не будем проверять вашу верстку через этот браузер. 

### Модальные окна
Все элементы которые предполагают вызов модального окна, должны его вызывать. В данном макете модальное окно должно вызываться на кнопку “войти” и содержать рабочую форму обратной связи. Как выглядят модальные окна, вы найдете в макете лендинга. Если отсутствует модальное окно, вам нужно его создать самостоятельно. Модальное окно не должно выбиваться из стиля всего сайта. Модальное окно должно закрываться при нажатии на клавишу esc, а также при клике мимо окна.

### Формы обратной связи
Все формы, которые заполняет пользователь на сайте, должны быть рабочими и отправлять письмо на почту заказчика. Отправлять данные нужно через SMTP-скрипт, чтобы письма не попадали в папку спам. 

Все обязательные поля форм должны проходить валидацию: пустая или заполненная неверно форма не должна отправляться с сайта. Выводите подсказки для пользователя, если неверно заполнено поле. Для полей ввода номера телефона должна быть подключена маска
 
После успешной отправки формы, пользователь должен попасть на страницу благодарности. На странице благодарности должна присутствовать кнопка возвращения на главную страницу

### Номера телефонов и e-mail на сайте
Все телефоны и e-mail адреса, которые встречаются на сайте должны быть оформлены в виде ссылок: 

```html
<a href="mailto:example@example.com">Example Email</a> 
<a href="tel:01234567890">01234 567 890</a>
```

---

Если после прочтения требований и просмотра макета у вас не осталось вопросов, оставьте комментарий к задаче с формулировкой:
```
Вопросов нет. Макет продублировал к себе. С требованиями ознакомился.
```

После чего передвиньте задачу в столбец `Готово` и ожидайте проверки куратором.

**Comment by xstupidkidzx** [comment]
У меня возник вопрос, а как продублировать макет фигмы в свой аккаунт?

**Comment by xdpugachevx-coach** [comment]
> У меня возник вопрос, а как продублировать макет фигмы в свой аккаунт?

Необходимо нажать такую-то кнопку там-то

**Comment by xdpugachevx-coach** [comment]
Задача выполнена некорректно, требуется оставить комментарий о том, что макет продублирован

**Comment by xstupidkidzx** [comment]
Вопросов нет. Макет продублировал к себе. С требованиями ознакомился.
